### ISSUE TITLE
Windows Installation Issue

### ISSUE THREAD

**Issue by bilal1976** [Zeukkari/leapgim#12]
I am trying to install leapgim, its been two full days but not yet succeeded. Actually everything is new for me. I found your project very powerful solution in order to program leap as replacement for mouse and key board.
Can you please share some more details for installation the leapgim on windows 7 32/64 bit platform. I tried to install exact version specified in Troubleshooting Dependencies, but no success. Please, can you write complete installation details considering a newbie. 

Appreciate and thanks.

**Comment by Zeukkari** [comment]
This project is a rough diamond. The dependency issues related to the mouse & keyboard IO component (robot.js and previously node-java) have been a major nuisance. 

Can you post the console output from npm install leapgim ?

**Comment by bilal1976** [comment]
Thanks for your kind prompt response. I install the project several time. Googled different errors. So to fulfill the prerequisites dependencies I did a lot of things. Installed Windows 7.1 SDK with Microsoft Visual C++ Redistributable 10.0.0.30319 and VC-Compiler-KB2519277. Then installed Visual Studio 10 and so on. Several time uninstalled and reinstalled these softwares. Every time I am getting different errors. The most recent npm-debug.log is as below.
   0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart leapgim@0.1.5
6 info start leapgim@0.1.5
7 verbose unsafe-perm in lifecycle true
8 info leapgim@0.1.5 Failed to exec start script
9 verbose stack Error: leapgim@0.1.5 start: `npm run build && nw .`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid leapgim@0.1.5
11 verbose cwd C:\Users\Bilal Sadiq\Downloads\leapgim-master
12 error Windows_NT 10.0.10586
13 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
14 error node v4.2.3
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error leapgim@0.1.5 start: `npm run build && nw .`
17 error Exit status 1
18 error Failed at the leapgim@0.1.5 start script 'npm run build && nw .'.
18 error This is most likely a problem with the leapgim package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run build && nw .
18 error You can get their info via:
18 error     npm owner ls leapgim
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Appreciate your concerns.

**Comment by bilal1976** [comment]
I am trying and trying. Attached is the log file. 
[npm-debug-log.docx](https://github.com/Zeukkari/leapgim/files/97008/npm-debug-log.docx)

**Comment by Zeukkari** [comment]
I can't get Robot.js to compile using nw-gyp, which seems to be the problem.

I'll take another shot at this on weekend, but Im not very experienced compiling things in a windows environment. This seems to be a good resource: https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md. The Robot.js issue tracker (https://github.com/octalmage/robotjs/issues) might contain others.

Meanwhile I would suggest testing this thing with another OS. This thing has been developed in Ubuntu and briefly tested on OS X.

**Comment by postmaxin** [comment]
FYI, I'm having problems with getting it to compile in Ubuntu Wily as well. I've installed robotjs and it's dependencies successfully, but it looks like leapgim is depending on an older or different version of robotjs and therefore can't proceed.

This is my first time using npm -- the log it leaves in my home directory doesn't really give me too much information to go on. I'll check back once I've had a chance to play with it a little bit more.

**Comment by Zeukkari** [comment]
Latest development efforts with updated libraries are available on this branch: https://github.com/Zeukkari/leapgim/tree/deprecate-nwjs

I figured I'd drop nw.js since it's potential was never really leveraged and it's only used to play sound effects currently.

**Comment by bilal1976** [comment]
Thanks, i am trying and will update accordingly.

**Comment by bilal1976** [comment]
I am still getting errors attached is the log file. Really appreciate your concerns. Now started looking into the robotjs file.
[log.docx](https://github.com/Zeukkari/leapgim/files/99146/log.docx)

**Comment by postmaxin** [comment]
It's working for me now, thank you!

FYI, on Ubuntu Wily, the help window it pops up on startup is tiny and cannot be resized:

![yaaay](https://cloud.githubusercontent.com/assets/1660387/12510542/a5ae9c34-c0d8-11e5-8e79-f5829a8097e2.png)

**Comment by Zeukkari** [comment]
Yeah.. there isn't really any content there.

**Comment by Zeukkari** [comment]
I deprecated NW.js and made a new release. There shouldn't be any outstanding issues regarding Windows installation. Can you test it?

**Comment by bilal1976** [comment]
node-gyp configure OK
node-gyp build (gives below errors, plz any further clue)

C:\Users\Administrator\Documents\GitHub\leapgim>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.0
gyp info using node@4.1.2 | win32 | ia32
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 2148734720
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roamin
g\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\Adminis
trator\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "build"

gyp ERR! cwd C:\Users\Administrator\Documents\GitHub\leapgim
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.0
gyp ERR! not ok

Installed:
Microsoft Visual Studio 2008
Microsoft Visual C++ 2008 Redistribution
Microsoft .Net Framework 3.5

Microsoft Windows 7 SDK 7.1
SDK 7.1 update

Thanks for your help.

**Comment by bilal1976** [comment]
I also tested on Windows 10 with VS2015 and python 2.7.11 x86 and 64

PLZ find attached the error details.
[Console-log.docx](https://github.com/Zeukkari/leapgim/files/102490/Console-log.docx)

**Comment by Zeukkari** [comment]
Im using windows 8.1, VS2015, node.js version 4.2.4 and npm version 2.14.12.

Node.js has issues with long file paths so moving the installation directory to the root level might help.

I seem to recall some errors comming from the robot.js installer, but the module seems to work regardless. Can you verify, in leapgim directory, that robot.js is not registered? Calling `require('robotjs').moveMouse(0,0)` should move the mouse pointer to the top left corner.

**Comment by bilal1976** [comment]
thanks for your reply.
Also installed ubuntu 14.04 LTS with node 4.2.6, npm 2.14.12 and node-gyp 3.0.0 but getting errors as attached. robotjs configuration and build is successful. when I run the command npm start from leapgim directory; it start listening on port 3000. But the index file only shows leap version as attached. of course there is errors to debug as below.
[leamgim-Ubuntu-14.04.pdf](https://github.com/Zeukkari/leapgim/files/103502/leamgim-Ubuntu-14.04.pdf)
![leapgim](https://cloud.githubusercontent.com/assets/7498146/12556963/a2453c9c-c399-11e5-9605-ee82cc6c3514.png)

**Comment by bilal1976** [comment]
Also on the windows 10 with MSVS2015, node 4.2.4, python 2.7.11, npm 2.14.12 and node-gyp 3.2.1; I am getting the attached errors. Node-gyp configure : command successful on leapgim directory. Robotjs configure and build successfully with node-gyp.  
[leapgim-log.docx](https://github.com/Zeukkari/leapgim/files/103524/leapgim-log.docx)

**Comment by Zeukkari** [comment]
Start Leap Control Panel. The tray location may be a little hard to find in Ubuntu.

```
LeapControlPanel &
```

If the leap daemon is not running, start it with:

```
sudo service leapd start
```

Tracking maybe paused. If the leap tray icon remains black, right click and select ´resume tracking´.

Verify that hand tracking is indeed working with the diagnostic visualizer.

Leapgim unfortunately doesn't provide much in terms of troubleshooting. The output from a functional setup looks like this:

![diagnostiikka2](https://cloud.githubusercontent.com/assets/3033037/12557607/60912176-c394-11e5-8e85-60124ba13b89.png)

**Comment by Zeukkari** [comment]
My Ubuntu installation is reporting node-gyp v3.2.1. Maybe try updating it -> https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp

This might provide additional help for windows installation: https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

**Comment by bilal1976** [comment]
Thanks Zeukkari for you help. Its really very nice work. 

I am still getting errors while building the project attached above against bufferutil.cc and validation.cc. What are these errors and how/why this project is running.

I tested some gesture those are working very fine. Can you please suggest me if I want to extend the keyboard buttons using gestures; what will be the starting point for me.

**Comment by Zeukkari** [comment]
Thank you.

I'm closing the issue since this is no longer relevant to Windows installation.

I'll gladly help with configuration issues. Please email me.
