### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by matanox** [Zeukkari/leapgim#6]
Hi Guys,

This project looks like it's already gotten some love.
Does this look anyway familiar? I guess some version incompatibility issue.

> npm install -g leapgim
> .
> .
> .
> 
> ```
> CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
> In file included from ../src/java.h:9:0,
>                  from ../src/java.cpp:1:
> ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
> ../node_modules/nan/nan.h:342:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
>      return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
>                                                                               ^
> ../node_modules/nan/nan.h:342:78: note: candidate is:
> In file included from ../src/java.h:5:0,
>                  from ../src/java.cpp:1:
> .../.node-gyp/4.1.0/include/node/v8.h:4675:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
>    static Local<Signature> New(
>                            ^
> .../.node-gyp/4.1.0/include/node/v8.h:4675:27: note:   candidate expects 2 arguments, 4 provided
> In file included from ../src/java.h:9:0,
>                  from ../src/java.cpp:1:
> ../node_modules/nan/nan.h: At global scope:
> ../node_modules/nan/nan.h:424:3: error: redefinition of ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’
>    NanNew<v8::StringObject, v8::Handle<v8::String> >(
>    ^
> ../node_modules/nan/nan.h:417:3: error: ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’ previously declared here
>    NanNew<v8::StringObject, v8::Local<v8::String> >(
>    ^
> ../node_modules/nan/nan.h:442:36: error: redefinition of ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
>    NAN_INLINE v8::Local<v8::RegExp> NanNew(
>                                     ^
> ../node_modules/nan/nan.h:436:36: error: ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
>    NAN_INLINE v8::Local<v8::RegExp> NanNew(
>                                     ^
> ../node_modules/nan/nan.h:454:36: error: redefinition of ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
>    NAN_INLINE v8::Local<v8::RegExp> NanNew(
>                                     ^
> ../node_modules/nan/nan.h:448:36: error: ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
>    NAN_INLINE v8::Local<v8::RegExp> NanNew(
>                                     ^
> ../node_modules/nan/nan.h:623:19: error: ‘NanNew’ declared as an ‘inline’ variable
>        v8::String::ExternalAsciiStringResource *resource) {
>                    ^
> ../node_modules/nan/nan.h:623:19: warning: ‘always_inline’ attribute ignored [-Wattributes]
> ../node_modules/nan/nan.h:623:19: error: ‘v8::Local<v8::String> NanNew’ redeclared as different kind of symbol
> ../node_modules/nan/nan.h:617:36: error: previous declaration of ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’
>    NAN_INLINE v8::Local<v8::String> NanNew(
>                                     ^
> ../node_modules/nan/nan.h:623:7: error: ‘ExternalAsciiStringResource’ is not a member of ‘v8::String’
>        v8::String::ExternalAsciiStringResource *resource) {
>        ^
> ../node_modules/nan/nan.h:623:48: error: ‘resource’ was not declared in this scope
>        v8::String::ExternalAsciiStringResource *resource) {
>                                                 ^
> ../node_modules/nan/nan.h:637:27: error: redefinition of ‘template<class T> v8::Local<T> _NanEscapeScopeHelper(v8::Local<T>)’
>    NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
>                            ^
> ../node_modules/nan/nan.h:632:27: error: ‘template<class T> v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T>)’ previously declared here
>    NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T> val) {
>                            ^
> ```

I don't mind installing directly from the repo, but not sure if the installation and running instructions are up-to-date, so maybe you can confirm, and/or say if you keep a certain branch stable.

`gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)`

`javac 1.7.0_80` but I also have java 8 if that's preferred.

Just installed the latest LeapMotion from https://developer.leapmotion.com/downloads/skeletal-beta?platform=linux&version=2.3.1.31549.

Thanks for having a look!

**Comment by Zeukkari** [comment]
The instructions aren't up-to-date. 

We recently decided to rewrite the whole thing from scratch and renamed the previous repository to leapgim-legacy. If you're comming from npm then you're propably looking at the wrong repository. 

The legacy version uses node-java-bridge to generate mouse events, while the newer version uses robot.js. With the legacy version installation should function if you can just figure out issues with the node-java module. Check their repo for troubleshooting help: https://github.com/joeferner/node-java

We're actively working on a new release.

**Comment by matanox** [comment]
Thanks Timo. Should I then assume the "legacy" version had some fundumental
issues making it worthwhile waiting for the next one?

**Comment by Zeukkari** [comment]
I wouldn't say there were any fundamental issues. The greatest issue I had with the legacy version was node-java package installation. If you wanna use leap motion to control the mouse and you manage to install the node-java package then it should be worthwhile to check out.

The new version will notably utilize a client-server model in the spirit on IoT, and will include a GUI.

About the actual error: I'm making an educated guess that this is related to updated node.js versions. You could try downgrading to node.js to 0.10.x and see if the installer works. There's handy tools for that available on npm: https://www.npmjs.com/package/n

**Comment by matanox** [comment]
Thanks, but I think those compilation errors were not related. Maybe you'd
care sharing your versions of things similar to those I specified there, to
expedite my orientation.. one thing I wonder about is whether I really need
to install globally in npm (I am not aware this can be done without
downgrading nodejs globally, whereas a local installation can use nvm for
its own older version of node).

I hope you may have the patience to answer.
I'd really like to get it running :)

**Comment by Zeukkari** [comment]
https://github.com/Zeukkari/leapgim/wiki/Troubleshooting-dependencies

**Comment by Zeukkari** [comment]
You shouldn't need to install this globally. The global installation is probably related to having node-gyp in $PATH or some similar anti-pattern in my code.

The coffeescript version hasn't even been installed globally during testing yet. The local version works just fine and in the legacy code there must be something silly that would require global installation.

**Comment by Zeukkari** [comment]
The head of the master branch in this repository should install without errors.
